### ISSUE TITLE
Retrieve the machine model from /proc/cpuinfo instead of /proc/device-tree/model

### ISSUE THREAD

**Issue by sanomiya** [IBM/CAST#101]
In some easier versions of the node motherboard, /proc/device-tree/model returns all 0s.
/proc/cpuinfo always returns the correct model.

**Comment by fpizzano** [comment]
@besawn do we have a better recommendation after running latest GFW ?

**Comment by besawn** [comment]
@fpizzano The model that @sanomiya is referencing in this issue is the server model and is not related to the processor inventory. There haven't been any recent firmware changes related to the server model handling that I am aware of. CSM inventory is using /proc/device-tree/model.

I recall this being an issue for earlier server types, but I don't recall seeing it on any P9 servers. Let's discuss during the next team meeting.
