### ISSUE TITLE
rpm build for CSM Kibana plugins

### ISSUE THREAD

**Issue by fpizzano** [IBM/CAST#334]
**Summary:**
rpm build for Kibaba use cases

**Comment by fpizzano** [comment]
@morrone

**Comment by mew2057** [comment]
First draft of the rpm has been successfully built, changes are currently in a branch on my forked repo.

**Comment by morrone** [comment]
@mew2057, can you give me a pointer to which branch that is on?

**Comment by mew2057** [comment]
https://github.com/mew2057/CAST/tree/bds-rpms

**Comment by mew2057** [comment]
To build your environment needs nodejs, we're currently using a binary tarball for node on power that I found on the node site [node-v6.0.0-linux-ppc64le.tar.xz](https://nodejs.org/dist/v6.0.0/node-v6.0.0-linux-ppc64le.tar.xz).

**Comment by morrone** [comment]
I don't think that we should see the conditionals "if [ -f /usr/share/kibana/bin/kibana-plugin ]" in the pre/post install scripts.  Instead this kibana plugin rpm should have an explicit requirement on the kibana package to _ensure_ that kibana is installed.  Otherwise yum will have no idea that there is a package ordering requirement.

Without the proper dependency on kibana expressed in the rpm, when yum is told to install both the kibana and the csm-kibana-plugin rpm packages, it may very well install the csm-kibanan-plugin _before_ kibana.  In that case our sysadmins will be left scratching their heads because both packages look like they are installed, but kibana will say that the plugin does not exist (because kibana was not installed at the time that kibana.post.install was run).

If we get lucky, they install in the right order and everything is fine.  Which means that the install will appear to work randomly to our sysadmins, and they will curse IBM.

Lets make the install deterministic. :)

Also, I would be much more keen to try building this myself if it was in a stand-alone repository, instead of requiring me to build the entire bds package which I have no interest in doing.

Further, this approach of having one mashup of multiple rpm packages built from a single source tree will very likely make this prohibitively difficult to built the plugin packages in our own local build farm.  That is highly undesirable.

If you persist in this approach it will likely mean that IBM has to accept the responsibility for rebuilding the plugins any time we wish, rather than us building them ourselves without bothering IBM support.

**Comment by morrone** [comment]
Any thoughts on the path forward?

**Comment by mew2057** [comment]
Install was made deterministic in the 1.3.0 release. There is currently no plan to split the plugin source into its own repository.

**Comment by morrone** [comment]
Can you please provide a link here for where the issue was resolved?  I'm looking at the cast_1.3.x branch, and it seems to still have the same issues that I raised 7 days ago.  What am I missing?

**Comment by mew2057** [comment]
We fixed it here:

https://github.com/IBM/CAST/commit/b19f29dc11186f25f449e0253a697ac3073f81ab

**Comment by mew2057** [comment]
This is the file that we set the dependency in: https://github.com/IBM/CAST/blob/b19f29dc11186f25f449e0253a697ac3073f81ab/csm_big_data/setupRPM.cmake

**Comment by morrone** [comment]
Why are the calls to the -plugin commands still wrapped in conditionals?  Those should be removed, correct?  If the command doesn't exist, we want the rpm install to fail so we _know_ that something went wrong.
